version: "2"

linters:
  enable:
    # Core linters for critical issues
    - bodyclose # Ensures HTTP response bodies are closed
    - errcheck # Detects unchecked error returns
    - govet # Examines Go source code and reports suspicious constructs
    - revive # Community-maintained replacement for golint
    - ineffassign # Detects ineffectual assignments
    - unconvert # Removes unnecessary type conversions
    - unused # Finds unused constants, variables, functions, types
